-- data for rooms from hotel_id 1 to 10. 
INSERT INTO room (price, amenities, capacity, view, extendable, hotel_id, damage) VALUES
(150.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'street View', True, 1, 'Minor damage to mini bar'),
(200.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'City View', TRUE, 1, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi', 5, 'mountain View', False, 1, NULL),
(180.00, 'Free Wi-Fi, TV, Air Conditioning', 2, 'City View', TRUE, 1, NULL),
(120.00, 'Free Wi-Fi, TV, Air Conditioning', 1, 'City View', TRUE, 1, 'Noisy air conditioning unit'),
(180.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 2, 'Street View', TRUE, 2, 'Unstable Wi-Fi connection'),
(220.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 3, 'Street View', TRUE, 2, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi', 4, 'Mountain View', FALSE, 2, NULL),
(190.00, 'Free Wi-Fi, TV, Air Conditioning', 1, 'Garden View', TRUE, 2, NULL),
(200.00, 'Free Wi-Fi, TV, Air Conditioning', 2, 'Street View', TRUE, 2, NULL),
(380.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 2, 'Mountain View', TRUE, 3, 'Unstable Wi-Fi connection'),
(350.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 3, 'Street View', TRUE, 3, NULL),
(400.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi', 4, 'Mountain View', FALSE, 3, NULL),
(260.00, 'Free Wi-Fi, TV, Air Conditioning', 1, 'Street View', TRUE,3, NULL),
(300.00, 'Free Wi-Fi, TV, Air Conditioning', 2, 'Garden View', TRUE, 3, NULL),
(180.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 2, 'Street View', TRUE, 4, NULL),
(220.00, 'Free Wi-Fi, TV, Air Conditioning', 3, 'Street View', TRUE, 4, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Sea View', TRUE, 4, NULL),
(150.00, 'Free Wi-Fi, TV, Air Conditioning', 1, 'Street View', TRUE, 4, NULL),
(350.00, 'Free Wi-Fi, TV, Air Conditioning', 5, 'Street View', FALSE, 4, NULL),
(180.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'City View', TRUE, 5, NULL),
(220.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Sea View', TRUE, 5, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi', 5, 'Mountain View', FALSE, 5, NULL),
(190.00, 'Free Wi-Fi, TV, Air Conditioning', 2, 'Garden View', TRUE, 5, NULL),
(200.00, 'Free Wi-Fi, TV, Air Conditioning', 1, 'Lake View', TRUE, 5, NULL),
(190.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 4, 'City View', TRUE, 6, NULL),
(210.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 3, 'Sea View', TRUE, 6, NULL),
(240.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi', 5, 'Mountain View', FALSE, 6, 'Unstable WIFI Connection'),
(200.00, 'Free Wi-Fi, TV, Air Conditioning', 2, 'Garden View', TRUE, 6, NULL),
(220.00, 'Free Wi-Fi, TV, Air Conditioning', 1, 'Lake View', TRUE, 6, NULL),
(200.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 2, 'City View', TRUE, 7, NULL),
(230.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Sea View', TRUE, 7, NULL),
(260.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi', 5, 'Mountain View', FALSE, 7, NULL),
(210.00, 'Free Wi-Fi, TV, Air Conditioning', 3, 'Garden View', TRUE, 7, NULL),
(240.00, 'Free Wi-Fi, TV, Air Conditioning', 1, 'Lake View', TRUE, 7, NULL),
(210.00, 'Free Wi-Fi, TV, Air Conditioning', 1, 'City View', TRUE, 8, 'TV is broken'),
(240.00, 'Free Wi-Fi, TV, Air Conditioning', 3, 'Sea View', TRUE, 8, NULL),
(270.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi', 4, 'Mountain View', FALSE, 8, NULL),
(220.00, 'Free Wi-Fi, TV, Air Conditioning', 2, 'Garden View', TRUE, 8, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 2, 'Lake View', TRUE, 8, NULL),
(150.00, 'Free Wi-Fi, TV, Air Conditioning', 1, 'City View', TRUE, 9, NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning', 2, 'City View', TRUE, 9, NULL),
(170.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi', 3, 'Street View', TRUE, 9, NULL),
(180.00, 'Free Wi-Fi, TV, Air Conditioning', 4, 'Garden View', TRUE, 9, NULL),
(190.00, 'Free Wi-Fi, TV, Air Conditioning', 5, 'Garden View', FALSE, 9, 'Noisy air conditioning unit'),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 1, 'Mountain View', TRUE, 10, NULL),
(260.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 2, 'Sea View', TRUE, 10, 'Broken coffee maker'),
(270.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi', 3, 'Mountain View', TRUE, 10, NULL),
(280.00, 'Free Wi-Fi, TV, Air Conditioning', 4, 'Mountain View', TRUE, 10, NULL),
(290.00, 'Free Wi-Fi, TV, Air Conditioning', 5, 'Mountain View', FALSE, 10, NULL); 



-- the value of room for hotel_id 11 to 20
INSERT INTO room (price, amenities, capacity, view, extendable, hotel_id, damage) VALUES
(200.00, 'Free Wi-Fi, TV, Air Conditioning', 1, 'Lake View', TRUE, 11, NULL),
(210.00, 'Free Wi-Fi, TV, Air Conditioning', 2, 'Lake View', TRUE, 11, NULL),
(220.00, 'Free Wi-Fi, TV, Air Conditioning', 3, 'Lake View', TRUE, 11, NULL),
(230.00, 'Free Wi-Fi, TV, Air Conditioning', 4, 'Garden View', TRUE, 11, NULL),
(240.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 5, 'Lake View', FALSE, 11, NULL),
(300.00, 'Free Wi-Fi, TV, Air Conditioning', 1, 'City View', TRUE, 12, NULL),
(310.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 2, 'City View', TRUE, 12, NULL),
(320.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi', 3, 'Mountain View', TRUE, 12, NULL),
(330.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 4, 'City View', TRUE, 12, 'Broken mini bar'),
(340.00, 'Free Wi-Fi, TV, Air Conditioning', 5, 'City View', FALSE, 12, NULL),
(400.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 1, 'City View', TRUE, 13, NULL),
(410.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 2, 'Lake View', TRUE, 13, NULL),
(420.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi', 3, 'Garden View', TRUE, 13, NULL),
(430.00, 'Free Wi-Fi, TV, Air Conditioning', 4, 'Garden View', TRUE, 13, NULL),
(440.00, 'Free Wi-Fi, TV, Air Conditioning', 5, 'Lake View', FALSE, 13, NULL),
(350.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 1, 'City View', TRUE, 14, NULL),
(360.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 2, 'City View', TRUE, 14, NULL),
(370.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi', 3, 'Garden View', TRUE, 14, NULL),
(380.00, 'Free Wi-Fi, TV, Air Conditioning', 4, 'City View', TRUE, 14, 'Leaking air conditioning'),
(390.00, 'Free Wi-Fi, TV, Air Conditioning', 5, 'City View', FALSE, 14, NULL),
(200.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 15, NULL),
(220.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 15, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Mountain View', False, 15, NULL),
(180.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 15, NULL),
(120.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 15, NULL),
(380.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 16, NULL),
(450.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 16, NULL),
(500.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Mountain View', False, 16, NULL),
(360.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 16, NULL),
(300.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 16, NULL),
(300.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 17, NULL),
(350.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 17, NULL),
(400.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Mountain View', False, 17, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 17, NULL),
(200.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 17, NULL),
(210.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 18, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 18, NULL),
(400.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Mountain View', False, 18,'broken AC'),
(180.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 18, NULL),
(150.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 18, NULL),
(350.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 19, NULL),
(380.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 19, NULL),
(420.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', False, 19,NULL),
(320.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 19, NULL),
(300.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 19, NULL),
(200.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 20, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 20, NULL),
(350.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', False, 20,NULL),
(165.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 20, NULL),
(150.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 20, 'Unstable wifi connection');


-- Hotel 21 to 30
INSERT INTO room (price, amenities, capacity, view, extendable, hotel_id, damage) VALUES
(220.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 21, NULL),
(260.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 21, NULL),
(350.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 21, NULL),
(165.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Mountain View', TRUE, 21, NULL),
(155.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 21, 'Leaking air conditioning'),
(210.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 22, NULL),
(255.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 22, NULL),
(345.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 22, NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 22, NULL),
(145.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 22, 'Unstable wifi connection'),
(230.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 23, NULL),
(265.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 23, NULL),
(355.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 23, NULL),
(170.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 23, NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 23, NULL),
(215.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 24, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 24, NULL),
(340.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 24, NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 24, NULL),
(150.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 24, 'Unstable wifi connection'),
(240.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 25, NULL),
(270.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 25, NULL),
(360.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 25, NULL),
(175.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 25, NULL),
(155.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 25, NULL),
(220.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 26, NULL),
(260.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 26, NULL),
(350.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 26, NULL),
(165.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Mountain View', TRUE, 26, 'Room service not available on Sundays'),
(155.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 26, NULL),
(210.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 27, NULL),
(255.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 27, NULL),
(345.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 27, NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 27, NULL),
(145.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 27, 'Noise from nearby construction'),
(230.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 28, NULL),
(265.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 28, NULL),
(355.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 28, NULL),
(170.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 28,NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 28,NULL),
(215.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 29, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 29, NULL),
(340.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 29, NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 29, 'Limited parking space'),
(150.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 29, NULL),
(240.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 30, NULL),
(270.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 30, NULL),
(360.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 30, NULL),
(175.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 30, 'Limited room service hours'),
(155.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 30, NULL);

-- Continue this pattern for hotels 31 through 40

-- Hotel 31
INSERT INTO room (price, amenities, capacity, view, extendable, hotel_id, damage) VALUES
(220.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 31, NULL),
(260.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 31, 'Room service not available on Sundays'),
(350.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 31, NULL),
(165.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Mountain View', TRUE, 31, NULL),
(155.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 31, NULL),
(210.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 32, NULL),
(255.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 32, NULL),
(345.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 32, NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 32, NULL),
(145.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 32, 'Noise from nearby construction'),
(230.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 33, NULL),
(265.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 33, 'Old-fashioned room décor'),
(355.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 33, NULL),
(170.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 33, NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 33, NULL),
(215.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 34, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 34, NULL),
(340.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 34, NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 34, NULL),
(150.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 34, NULL),
(240.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 35, NULL),
(270.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 35, NULL),
(360.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 35, NULL),
(175.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 35, NULL),
(155.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 35, 'Occasional Wi-Fi signal dropouts'),
(220.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 36, NULL),
(260.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 36, NULL),
(350.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 36, NULL),
(165.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Mountain View', TRUE, 36, NULL),
(155.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 36, NULL),
(210.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 37, NULL),
(255.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 37, NULL),
(345.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 37, NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 37, NULL),
(145.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 37, NULL),
(230.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 38, NULL),
(265.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 38, NULL),
(355.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 38, NULL),
(170.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 38, NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 38, NULL),
(215.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 39, NULL),
(250.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 39, NULL),
(340.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 39, NULL),
(160.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 39, NULL),
(150.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 39, NULL),
(240.00, 'Free Wi-Fi, TV, Air Conditioning, Mini Bar', 3, 'No View', TRUE, 40, NULL),
(270.00, 'Free Wi-Fi, TV, Air Conditioning, Coffee Maker', 4, 'Street View', TRUE, 40, NULL),
(360.00, 'Free Wi-Fi, TV, Air Conditioning, Jacuzzi, Bathrobe', 5, 'Sea View', FALSE, 40, NULL),
(175.00, 'Free Wi-Fi, TV, Air Conditioning, Desk', 2, 'Street View', TRUE, 40, NULL),
(155.00, 'Free Wi-Fi, TV, Air Conditioning, Safe Box', 1, 'Street View', TRUE, 40, NULL);




